name: Update Proxy IP Status

on:
  schedule:
    - cron: '0 0 */7 * *'  # Pengecekan setiap 7 hari sekali
  workflow_dispatch:

jobs:
  update-proxies:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'  # Gunakan Python 3.11 (versi stabil)

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Update proxy status
      env:
        IP_FILE: 'f74bjd2h2ko99f3j5'  # File input
        API_URL: 'https://proxyip-check.vercel.app/{ip}:{port}'  # API untuk pengecekan satu per satu
      run: |
        python update_proxy_status.py

    - name: Commit and push changes
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git add f74bjd2h2ko99f3j5
        git add error.txt
        if git diff --cached --exit-code; then
          echo "No changes to commit"
        else
          git commit -m "Update proxy IP status"
          git push
        fi
